### ISSUE TITLE
关于板块列表

### ISSUE THREAD

**Issue by nmb-xyz** [seven332/Nimingban#46]
- 在刷新板块列表的时候，忽视原来存在的板块 (`id`)，且在板块列表的最后面添加新板块。如果某些板块 `id` 从列表中消失则提示，但不要移除 — 主要是不要打乱原有的板块排序
 - 允许通过 `id` 和自定义的名称添加隐藏板块，例如 圈内 和 询问2

**Comment by whitfield1023** [comment]
所以说圈内id多少呢

**Comment by seven332** [comment]
| id  | 标题             |
|-----|------------------|
| 5   | 东方Project      |
| 1   | 询问             |
| 2   | 游戏             |
| 3   | 魔都CP9          |
| 4   | 综合版1          |
| 6   | VOCALOID         |
| 7   | 贴图             |
| 8   | 新番实况         |
| 9   | 霹雳             |
| 10  | Minecraft        |
| 11  | 推理             |
| 12  | 漫画             |
| 13  | COSPLAY          |
| 14  | 动画             |
| 98  | 姐妹1            |
| 15  | 妖都AD9          |
| 16  | AKB              |
| 17  | 二次创作         |
| 18  | 值班室           |
| 99  | 国漫             |
| 19  | 小说             |
| 20  | 欢乐恶搞         |
| 22  | LOL              |
| 23  | D3               |
| 24  | 索尼             |
| 25  | 任天堂           |
| 27  | WIKI             |
| 28  | 怪物猎人         |
| 29  | AC大逃杀         |
| 92  | 日麻             |
| 93  | 舰娘             |
| 94  | 工作情感         |
| 30  | 技术宅           |
| 31  | 影视             |
| 32  | 料理             |
| 33  | 体育             |
| 34  | MUG              |
| 35  | 音乐             |
| 36  | 询问2            |
| 102 | 女性向           |
| 37  | 军武             |
| 38  | 口袋妖怪         |
| 39  | 模型             |
| 40  | 貓版             |
| 41  | 一骑当先         |
| 42  | 意见反馈         |
| 43  | 回收站2          |
| 44  | WOW              |
| 45  | 卡牌桌游         |
| 46  | AC页游王国印记   |
| 47  | AC页游王者召唤   |
| 48  | MUGEN            |
| 49  | Falcom           |
| 50  | 紅白歌合戰       |
| 51  | WOT              |
| 53  | AC页游街机三国   |
| 54  | 摄影             |
| 55  | 声优             |
| 56  | 考试             |
| 57  | AC页游热血海贼王 |
| 58  | AC页游轩辕变     |
| 59  | 信喵之野望       |
| 60  | AC页游将神       |
| 61  | AC页游忍者疾风传 |
| 62  | AC页游禁书目录   |
| 63  | 扩散性百万亚瑟王 |
| 64  | GALGAME          |
| 65  | AC游戏侠物语     |
| 66  | 苍茫之境         |
| 67  | KKK德州扑克      |
| 68  | AC妖精的尾巴     |
| 69  | AC游戏横扫天下   |
| 70  | DOTA             |
| 71  | AC胜利十一人     |
| 72  | DNF              |
| 73  | EVE              |
| 74  | AC游戏SD高达     |
| 75  | 数码             |
| 76  | AC游戏暗黑西游   |
| 77  | AC游戏SD火影     |
| 78  | AC游戏大将军     |
| 79  | 沃土             |
| 80  | 炉石传说         |
| 81  | 都市怪谈         |
| 82  | AC游戏女神联盟   |
| 83  | 速报             |
| 84  | AC游戏仙侠道     |
| 85  | AC游戏死神狂潮   |
| 86  | 战争雷霆         |
| 87  | 轻小说           |
| 88  | 天台             |
| 89  | 日记             |
| 90  | 美漫             |
| 91  | 更新日志         |
| 95  | GTA5             |
| 96  | 圈内             |
| 97  | 女装             |
| 100 | SNH48            |
| 101 | LoveLive         |
| 103 | 文学             |
