### ISSUE TITLE
关于饼干

### ISSUE THREAD

**Issue by nmb-xyz** [seven332/Nimingban#48]
- 无饼干情况下第一次发串，获取到饼干后为什么不会立即发串？
 - 发串成功后，记录下饼干的 7 位 ID 并在设置中显示，同时保存饼干的时候文件名附带上饼干 ID（不过发串的 API 好像根本没有，更别说返回相关值了，~~所以说暂时忽略掉我上面的胡说八道就好~~

**Comment by seven332** [comment]
1. 这是两个独立的操作，等会我改下
2. API 没这功能，就算了
