### ISSUE TITLE
1.2.8版在WIFI环境下提示网络错误,无法刷出

### ISSUE THREAD

**Issue by Smallpath** [seven332/Nimingban#50]
网络错误时,版规与左拉栏图片均可正常刷出
流量情况下正常,1.2.6版WIFI环境正常

**Comment by seven332** [comment]
你的意思是说现在安装 1.2.6 WIFI环境正常，而不仅是当时 1.2.6 WIFI环境正常？

**Comment by wwleeguoz** [comment]
在手机的WiFi高级设置里改一下IP和DNS可以解决，我这里是魔都电信。

**Comment by Smallpath** [comment]
原来如此,确实是魔都电信的锅,已解决
