### ISSUE TITLE
ios岛新版的注目功能好棒呀 Hippo能不能参考下

### ISSUE THREAD

**Issue by 4679** [seven332/Nimingban#55]
(`ε´(つ*⊂)

**Comment by seven332** [comment]
啥叫注目功能？

**Comment by 4679** [comment]
你没上岛吗 就是被回复了有提醒(=ﾟωﾟ)=

On Feb 17, 2016 17:16, seven332 <notifications@github.com> wrote:

啥叫注目功能？

**Comment by seven332** [comment]
订阅里的？

**Comment by 4679** [comment]
就是和贴吧差不多啦 有人回复你就有提示(=ﾟωﾟ)=

**Comment by 4679** [comment]
我想了想 确实是 不知道贼贼贼是怎么实现的
