### ISSUE TITLE
优化域名解析

### ISSUE THREAD

**Issue by manageryzy** [seven332/Nimingban#60]
匿名版在教育网以及其他部分线路解析不正常，但是IP是通的，希望可以在程序里加上直接IP访问的方式

刚刚看了一下依赖的okhttp3，Address有指定DNS的功能，不过我没用过这个库啦
https://square.github.io/okhttp/3.x/okhttp/okhttp3/Address.html

**Comment by seven332** [comment]
看了下文档，给了 dns 的接口，应该可以弄个默认 ip。等明天再弄吧。

**Comment by seven332** [comment]
试试这个，把扩展名改成 apk 就行了
[app-test.zip](https://github.com/seven332/Nimingban/files/235925/app-test.zip)

**Comment by manageryzy** [comment]
版头图片还是有问题

![image](https://cloud.githubusercontent.com/assets/6567674/14818309/fa2ad672-0bee-11e6-9269-aedd976cfa4d.png)

**Comment by manageryzy** [comment]
[logcat-2016-04-26-20-40-43-782.txt](https://github.com/seven332/Nimingban/files/236582/logcat-2016-04-26-20-40-43-782.txt)
logcat在这里，不过似乎没什么有用的东西

**Comment by manageryzy** [comment]
好吧，第二次启动的时候图片就出来了

**Comment by seven332** [comment]
你拿模拟器刷岛呀

**Comment by manageryzy** [comment]
手机上怕玩坏啦，没准签名不一样没法安装什么的啦
